"""Added active field for clinics

Revision ID: 0cd467e15202
Revises: 0878af7f5ece
Create Date: 2020-09-15 13:57:49.807770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd467e15202'
down_revision = '0878af7f5ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic', 'active')
    # ### end Alembic commands ###
