"""Added foster species, bound phone numbers to clinic, added priority to phone numbers

Revision ID: 36ad23cbec5a
Revises: 66185b1f4036
Create Date: 2020-06-09 12:15:51.324237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ad23cbec5a'
down_revision = '66185b1f4036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foster_species',
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('species')
    )
    op.create_table('volunteers_vs_species',
    sa.Column('vol_id', sa.Integer(), nullable=False),
    sa.Column('foster_species', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['foster_species'], ['foster_species.species'], ),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('vol_id', 'foster_species')
    )
    op.add_column('phone_number', sa.Column('primary_contact', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_number', 'primary_contact')
    op.drop_table('volunteers_vs_species')
    op.drop_table('foster_species')
    # ### end Alembic commands ###
