"""empty message

Revision ID: 4a1d6288f3f5
Revises: bc40907207ff
Create Date: 2020-07-03 12:14:25.876228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1d6288f3f5'
down_revision = 'bc40907207ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_number',
    sa.Column('dial_code', sa.String(length=3), nullable=False),
    sa.Column('phone_number', sa.String(length=7), nullable=False),
    sa.Column('primary_contact', sa.Boolean(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('dial_code', 'phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_number')
    # ### end Alembic commands ###
