"""empty message

Revision ID: 66185b1f4036
Revises: 6ba91ac43d36
Create Date: 2020-06-07 15:28:24.335828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66185b1f4036'
down_revision = '6ba91ac43d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_vs_volunteers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_vs_volunteers',
    sa.Column('phone_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vol_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phone_number'], ['phone_number.phone_number'], name='phone_vs_volunteers_ibfk_1'),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], name='phone_vs_volunteers_ibfk_2'),
    sa.PrimaryKeyConstraint('phone_number', 'vol_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
