"""empty message

Revision ID: 6ba91ac43d36
Revises: 8340a86fa6f2
Create Date: 2020-06-04 14:47:18.977504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ba91ac43d36'
down_revision = '8340a86fa6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinic', 'area_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('clinic', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('clinic', 'name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.add_column('phone_number', sa.Column('dial_code', sa.Integer(), nullable=False))
    op.add_column('phone_number', sa.Column('volunteer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phone_number', 'volunteer', ['volunteer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_number', type_='foreignkey')
    op.drop_column('phone_number', 'volunteer_id')
    op.drop_column('phone_number', 'dial_code')
    op.alter_column('clinic', 'name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('clinic', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('clinic', 'area_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
