"""Added notes attribute to volunteer model

Revision ID: 81bf8988a021
Revises: 36ad23cbec5a
Create Date: 2020-06-09 17:17:55.717240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bf8988a021'
down_revision = '36ad23cbec5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'notes')
    # ### end Alembic commands ###
