"""initial schema

Revision ID: 8340a86fa6f2
Revises: 
Create Date: 2020-05-31 15:33:34.535533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8340a86fa6f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('area')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=80), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('black_listed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_last_contacted'), 'volunteer', ['last_contacted'], unique=False)
    op.create_table('areas_vs_volunteers',
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('vol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area'], ['area.area'], ),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('area', 'vol_id')
    )
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('area_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['area_name'], ['area.area'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_email'), 'clinic', ['email'], unique=True)
    op.create_index(op.f('ix_clinic_name'), 'clinic', ['name'], unique=True)
    op.create_table('phone_number',
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_table('phone_vs_volunteers',
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('vol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phone_number'], ['phone_number.phone_number'], ),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('phone_number', 'vol_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_vs_volunteers')
    op.drop_table('phone_number')
    op.drop_index(op.f('ix_clinic_name'), table_name='clinic')
    op.drop_index(op.f('ix_clinic_email'), table_name='clinic')
    op.drop_table('clinic')
    op.drop_table('areas_vs_volunteers')
    op.drop_index(op.f('ix_volunteer_last_contacted'), table_name='volunteer')
    op.drop_table('volunteer')
    op.drop_table('area')
    # ### end Alembic commands ###
