"""Resetting all migrations due to schema change

Revision ID: 9c8be9044575
Revises: 
Create Date: 2020-06-10 17:13:04.798495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8be9044575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('areas', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('areas')
    )
    op.create_table('foster_species',
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('species')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=80), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('black_listed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_last_contacted'), 'volunteer', ['last_contacted'], unique=False)
    op.create_table('areas_vs_volunteers',
    sa.Column('areas', sa.String(length=80), nullable=False),
    sa.Column('vol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['areas'], ['areas.areas'], ),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('areas', 'vol_id')
    )
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('area_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['area_name'], ['areas.areas'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_email'), 'clinic', ['email'], unique=True)
    op.create_index(op.f('ix_clinic_name'), 'clinic', ['name'], unique=True)
    op.create_table('volunteers_vs_species',
    sa.Column('vol_id', sa.Integer(), nullable=False),
    sa.Column('foster_species', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['foster_species'], ['foster_species.species'], ),
    sa.ForeignKeyConstraint(['vol_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('vol_id', 'foster_species')
    )
    op.create_table('phone_number',
    sa.Column('dial_code', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('primary_contact', sa.Boolean(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('dial_code', 'phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_number')
    op.drop_table('volunteers_vs_species')
    op.drop_index(op.f('ix_clinic_name'), table_name='clinic')
    op.drop_index(op.f('ix_clinic_email'), table_name='clinic')
    op.drop_table('clinic')
    op.drop_table('areas_vs_volunteers')
    op.drop_index(op.f('ix_volunteer_last_contacted'), table_name='volunteer')
    op.drop_table('volunteer')
    op.drop_table('foster_species')
    op.drop_table('areas')
    # ### end Alembic commands ###
